const SB_URL = Deno.env.get('SUPABASE_URL')!;
const SB_KEY = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
const UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/151 Safari/537.36';
const MONTHS:any = { gennaio:'01',febbraio:'02',marzo:'03',aprile:'04',maggio:'05',giugno:'06',luglio:'07',agosto:'08',settembre:'09',ottobre:'10',novembre:'11',dicembre:'12',gen:'01',feb:'02',mar:'03',apr:'04',mag:'05',giu:'06',lug:'07',ago:'08',set:'09',ott:'10',nov:'11',dic:'12' };
const HIGH = /spider|avengers|marvel|wolverine|x-men|deadpool|fantastic four|batman|superman|harry potter|star wars|avatar|jurassic|pokemon|pokémon|mario|zelda|sonic|grand theft auto|gta|resident evil|assassin|call of duty|god of war|hollow knight|minecraft|disney|pixar|toy story|masters of the universe|minions|clayface/i;

type E={title:string,date:string,category:string,source:string,url:string,notes:string};
function romeParts(){ const p=new Intl.DateTimeFormat('en-GB',{timeZone:'Europe/Rome',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',hour12:false,weekday:'short'}).formatToParts(new Date()); const o:any={}; for(const x of p)o[x.type]=x.value; return {date:`${o.year}-${o.month}-${o.day}`,hour:Number(o.hour),weekday:o.weekday}; }
function decode(s:string){ return s.replace(/&nbsp;|&#160;/gi,' ').replace(/&amp;/g,'&').replace(/&#39;|&apos;/g,"'").replace(/&quot;/g,'"').replace(/&#8211;|&#x2013;/gi,'–').replace(/&#8212;|&#x2014;/gi,'—').replace(/&#176;|&deg;/gi,'°'); }
function strip(s:string){ return decode(s.replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ')).replace(/\s+/g,' ').trim(); }
function norm(s:string){ return decode(s).toLowerCase().split('—')[0].replace(/25mo/g,'25').replace(/25°/g,'25').replace(/[^a-z0-9à-ÿ]+/g,' ').trim(); }
function similar(a:string,b:string){ const x=norm(a),y=norm(b); if(x===y)return true; const n=Math.min(28,x.length,y.length); return n>=14 && x.slice(0,n)===y.slice(0,n); }
function parseDate(s:string,defaultYear?:number){ const m=s.trim().toLowerCase().match(/(\d{1,2})\s+([a-zà-ÿ]+)(?:\s+(\d{4}))?/i); if(!m)return null; const mon=MONTHS[m[2]]; if(!mon)return null; const y=m[3]||String(defaultYear||new Date().getFullYear()); return `${y}-${mon}-${String(m[1]).padStart(2,'0')}`; }
function inWindow(d:string){ const t=Date.parse(d+'T00:00:00Z'),now=Date.now()-86400000,end=Date.now()+365*86400000; return Number.isFinite(t)&&t>=now&&t<=end; }
async function fetchText(url:string){ const r=await fetch(url,{headers:{'user-agent':UA,'accept-language':'it-IT,it;q=0.9,en;q=0.8'}}); if(!r.ok)throw new Error(`${r.status} ${url}`); return await r.text(); }
async function sb(path:string,init:RequestInit={}){ const h=new Headers(init.headers||{}); h.set('apikey',SB_KEY); h.set('authorization',`Bearer ${SB_KEY}`); if(init.body)h.set('content-type','application/json'); const r=await fetch(`${SB_URL}/rest/v1/${path}`,{...init,headers:h}); const t=await r.text(); if(!r.ok)throw new Error(`Supabase ${r.status}: ${t.slice(0,500)}`); return t?JSON.parse(t):null; }
function priority(s:string){ if(/spider|avengers|gta|grand theft auto|batman|harry potter|star wars|pokemon|pokémon|wolverine|mario/.test(s.toLowerCase()))return 10; return 9; }

async function marvel():Promise<E[]>{ const out:E[]=[]; try{ const text=strip(await fetchText('https://www.marvel.com/movies')); const re=/(Avengers: Doomsday|Avengers: Secret Wars|Spider-Man: Brand New Day)[^A-Z0-9]{0,60}(JAN|FEB|MAR|APR|MAY|JUN|JUL|AUG|SEP|OCT|NOV|DEC)\s+(\d{1,2}),\s+(\d{4})/gi; const mm:any={JAN:'01',FEB:'02',MAR:'03',APR:'04',MAY:'05',JUN:'06',JUL:'07',AUG:'08',SEP:'09',OCT:'10',NOV:'11',DEC:'12'}; let m; while((m=re.exec(text))){ const d=`${m[4]}-${mm[m[2].toUpperCase()]}-${String(m[3]).padStart(2,'0')}`; if(inWindow(d))out.push({title:m[1],date:d,category:'Film/Serie',source:'live-film',url:'https://www.marvel.com/movies',notes:'Data confermata dalla pagina ufficiale Marvel Movies.'}); } }catch{} return out; }

async function warner():Promise<E[]>{ const out:E[]=[]; try{ const html=await fetchText('https://www.warnerbros.it/prossime-uscite/'); const re=/<a\b[^>]*>([\s\S]*?)<\/a>/gi; let m; while((m=re.exec(html))){ const t=strip(m[1]); const dm=t.match(/(\d{1,2}\s+(?:Gennaio|Febbraio|Marzo|Aprile|Maggio|Giugno|Luglio|Agosto|Settembre|Ottobre|Novembre|Dicembre)\s+\d{4})$/i); if(!dm)continue; const d=parseDate(dm[1]); const title=t.slice(0,t.length-dm[1].length).trim(); if(d&&inWindow(d)&&title&&HIGH.test(title))out.push({title,date:d,category:'Film/Serie',source:'live-film',url:'https://www.warnerbros.it/prossime-uscite/',notes:'Data confermata da Warner Bros. Entertainment Italia.'}); } }catch{} return out; }

async function playstation():Promise<E[]>{ const out:E[]=[]; try{ const html=await fetchText('https://www.playstation.com/it-it/ps5/games/'); const heads:[number,number,string][]=[]; const re=/<h([1-6])\b[^>]*>([\s\S]*?)<\/h\1>/gi; let m; while((m=re.exec(html))){ const title=strip(m[2]).replace(/[™®]/g,'').trim(); heads.push([m.index,re.lastIndex,title]); }
    for(let i=0;i<heads.length;i++){ const [start,end,title]=heads[i]; if(!title||!HIGH.test(title))continue; const next=heads[i+1]?.[0]??Math.min(html.length,end+2500); const segment=strip(html.slice(end,next)); const dm=segment.match(/Data di uscita\s*:\s*(\d{1,2}\s+[A-Za-zÀ-ÿ]+\s+\d{4})/i); if(!dm)continue; const d=parseDate(dm[1]); if(d&&inWindow(d))out.push({title,date:d,category:'Gaming',source:'live-gaming',url:'https://www.playstation.com/it-it/ps5/games/',notes:'Data confermata dalla pagina ufficiale PlayStation Italia.'}); }
  }catch{} return out; }

async function theSpace():Promise<E[]>{ const out:E[]=[]; try{ const text=strip(await fetchText('https://www.thespacecinema.it/notizie-concorsi/film-del-2026')); const re=/([A-ZÀ-Ý][A-Za-zÀ-ÿ0-9:'’&.\- ]{2,70})\s*\((\d{1,2}\s+[a-zà-ÿ]+)\)/g; let m; while((m=re.exec(text))){ const title=m[1].trim().replace(/^(con|di|e|arriva|arrivano|concludiamo il mese con|preparati al ritorno degli amici di sempre con)\s+/i,'').trim(); const d=parseDate(m[2],2026); if(d&&inWindow(d)&&HIGH.test(title))out.push({title,date:d,category:'Cinema/Merch',source:'cinema-merch',url:'https://www.thespacecinema.it/notizie-concorsi/film-del-2026',notes:'Data presente nel calendario ufficiale The Space Cinema 2026; utile per pianificare prodotti e contenuti a tema.'}); }
    const home=strip(await fetchText('https://www.thespacecinema.it/')); const g=/NOVITÀ\s*(\d{1,2})\s+(gen|feb|mar|apr|mag|giu|lug|ago|set|ott|nov|dic)\s+(2026|2027)\s+(Gadget|Menù)\s+(.{3,80}?)(?=\s+NOVITÀ|\s+INIZIATIVE|\s+OFFERTE|$)/gi; let x; while((x=g.exec(home))){ const d=parseDate(`${x[1]} ${x[2]} ${x[3]}`); const title=`${x[4]} ${x[5].trim()}`; if(d&&inWindow(d)&&HIGH.test(title))out.push({title,date:d,category:'Cinema/Merch',source:'cinema-merch',url:'https://www.thespacecinema.it/',notes:'Iniziativa merchandising rilevata sulla homepage ufficiale The Space Cinema.'}); }
  }catch{} return out; }

async function run(){ const groups=await Promise.all([marvel(),warner(),playstation(),theSpace()]); const unique:E[]=[]; for(const e of groups.flat()){ if(!unique.some(x=>x.date===e.date&&similar(x.title,e.title)))unique.push(e); }
  const existing=await sb('market_events?select=id,title,event_date,user_id,auto_generated,source&limit=500')||[]; const userId=existing.find((x:any)=>x.user_id)?.user_id; if(!userId)throw new Error('Nessun user_id disponibile in market_events'); let inserted=0,updated=0;
  for(const e of unique){ const match=existing.find((x:any)=>similar(String(x.title),e.title)); if(match){ if(match.event_date!==e.date && match.auto_generated===true && ['live-film','live-gaming','cinema-merch'].includes(match.source)){ await sb(`market_events?id=eq.${match.id}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({event_date:e.date,category:e.category,lead_days:45,priority:priority(e.title),notes:`${e.notes} Fonte: ${e.url}`,source:e.source})}); updated++; } continue; }
    await sb('market_events',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify([{user_id:userId,title:`${e.title}${e.category==='Gaming'?' — uscita videogioco':e.category==='Film/Serie'?' — uscita cinema':''}`,event_date:e.date,category:e.category,lead_days:45,priority:priority(e.title),notes:`${e.notes} Fonte: ${e.url}`,auto_generated:true,source:e.source}])}); inserted++; }
  return {found:groups.flat().length,unique:unique.length,inserted,updated,sources:{marvel:groups[0].length,warner:groups[1].length,playstation:groups[2].length,theSpace:groups[3].length}}; }
Deno.serve(async(req)=>{ try{ const r=romeParts(),force=new URL(req.url).searchParams.get('force')==='1'; if(!force&&!(r.weekday==='Mon'&&r.hour===7))return Response.json({ok:true,skipped:true,reason:'Fuori finestra lunedì 07:xx Europe/Rome',rome:r}); return Response.json({ok:true,...await run(),rome:r}); }catch(e){return Response.json({ok:false,error:String(e)},{status:500});} });